# -*- mode: ruby -*-
# vi: set ft=ruby :
servers=[
  {
    :hostname => "ansible-server",
    :ip => "192.168.100.10",
    :box => "centos/7",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "ansible-node",
    :ip => "192.168.100.11",
    :box => "centos/7",
    :ram => 1024,
    :cpu => 2
  }
]
Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "public_network"
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
            end
        config.vm.provision "shell", inline: <<-SHELL
            sudo yum install -y docker ansible net-tools git
            sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config 
            sudo service sshd restart
            sudo service docker restart
        SHELL
        end
    end
end
