---
- hosts: webservers  # Host or Group of Selections
  become: true
  vars:
    httpd_port: 8080
  tasks:
  - name: Install httpd # Naming the task for debug purpose
    yum: name=httpd state=present  # Using module ( doing the task )
  - name: Start httpd
    service: name=httpd state=started enabled=yes


- hosts: appserver
  become: true
  tasks:
  - name: Install default-jdk
    yum: name=java-1.8.0-openjdk state=present

